# Buildpack API version
api = "0.5"

# Buildpack ID and metadata
[buildpack]
id = "b-nova.com/go-sample"
version = "0.0.1"
name = "Go Sample"

# Stacks that the buildpack will work with
[[stacks]]
id = "io.buildpacks.samples.stacks.bionic"
